export enum UserRole {
    GENERATOR_OWNER = "GENERATOR_OWNER",
    BILL_COLLECTOR = "BILL_COLLECTOR",
    ADMIN = "ADMIN",
}

export enum SubscriberStatus {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
}

export enum BillStatus {
    PENDING = "PENDING",
    CANCELLED = "CANCELLED",
    PAID = "PAID",
}

export enum BillingModel {
    FIXED = "Fixed",
    METERED = "Metered",
}

export enum SmsCampaignStatus {
    COMPLETED = "COMPLETED",
    PENDING = "PENDING",
    PROCESSING = "PROCESSING",
    FAILED = "FAILED",
}

export enum SmsMessageStatus {
    FAILED = "FAILED",
    DELIVERED = "DELIVERED",
    SENT = "SENT",
    PENDING = "PENDING"
}

export enum LookupDomain {
    BILL_STATUS = "BILL_STATUS",
    BILLING_CYCLE_STATUS = "BILLING_CYCLE_STATUS",
    BILLING_MODE = "BILLING_MODE",
    GO_STATUS = "GO_STATUS",
    PAYMENT_METHOD = "PAYMENT_METHOD",
    SMS_CAMP_SEL_CRITERIA = "SMS_CAMP_SEL_CRITERIA",
    SMS_CAMPAIGN_STATUS = "SMS_CAMPAIGN_STATUS",
    SMS_JOB_STATUS = "SMS_JOB_STATUS",
    SMS_STATUS = "SMS_STATUS",
    SMS_TEMPLATE_VARIABLE = "SMS_TEMPLATE_VARIABLE",
    SUBSCRIBER_STATUS = "SUBSCRIBER_STATUS",
    USER_ROLE = "USER_ROLE",
    WALLET_TRANSACTION_TYPE = "WALLET_TRANSACTION_TYPE",
}
